// This file is automatically generated. DO NOT EDIT.

package interlis

type Transfer struct {
	HeaderSection HeaderSection `xml:"HEADERSECTION"`
	DataSection   DataSection   `xml:"DATASECTION"`
}

type HeaderSection struct {
	Sender  string   `xml:"SENDER,attr"`
	Version float64  `xml:"VERSION,attr"`
	Models  struct{} `xml:"MODELS"`
}

type DataSection struct {
	GM0321ComprehensiveComprehensive GM0321ComprehensiveComprehensive `xml:"GM03_2_1Comprehensive.Comprehensive"`
}

type GM0321ComprehensiveComprehensive struct {
	BID                                                                 string                                                              `xml:"BID,attr"`
	GM0321CoreCoreMDMetadata                                            GM0321CoreCoreMDMetadata                                            `xml:"GM03_2_1Core.Core.MD_Metadata"`
	GM0321CoreCoreMDDistribution                                        GM0321CoreCoreMDDistribution                                        `xml:"GM03_2_1Core.Core.MD_Distribution"`
	GM0321CoreCoreMDDistributiondistributionFormat                      GM0321CoreCoreMDDistributiondistributionFormat                      `xml:"GM03_2_1Core.Core.MD_DistributiondistributionFormat"`
	GM0321ComprehensiveComprehensiveMDFormat                            GM0321ComprehensiveComprehensiveMDFormat                            `xml:"GM03_2_1Comprehensive.Comprehensive.MD_Format"`
	GM0321ComprehensiveComprehensiveMDDigitalTransferOptions            GM0321ComprehensiveComprehensiveMDDigitalTransferOptions            `xml:"GM03_2_1Comprehensive.Comprehensive.MD_DigitalTransferOptions"`
	GM0321CoreCoreCIOnlineResource                                      []GM0321CoreCoreCIOnlineResource                                    `xml:"GM03_2_1Core.Core.CI_OnlineResource"`
	GM0321CoreCoreMDMetadatacontact                                     GM0321CoreCoreMDMetadatacontact                                     `xml:"GM03_2_1Core.Core.MD_Metadatacontact"`
	GM0321CoreCoreCIResponsibleParty                                    []GM0321CoreCoreCIResponsibleParty                                  `xml:"GM03_2_1Core.Core.CI_ResponsibleParty"`
	GM0321CoreCoreCIAddress                                             []GM0321CoreCoreCIAddress                                           `xml:"GM03_2_1Core.Core.CI_Address"`
	GM0321CoreCoreCIContact                                             []GM0321CoreCoreCIContact                                           `xml:"GM03_2_1Core.Core.CI_Contact"`
	GM0321CoreCoreCITelephone                                           []GM0321CoreCoreCITelephone                                         `xml:"GM03_2_1Core.Core.CI_Telephone"`
	GM0321ComprehensiveComprehensiveMDVectorSpatialRepresentation       GM0321ComprehensiveComprehensiveMDVectorSpatialRepresentation       `xml:"GM03_2_1Comprehensive.Comprehensive.MD_VectorSpatialRepresentation"`
	GM0321ComprehensiveComprehensiveMDGeometricObjects                  GM0321ComprehensiveComprehensiveMDGeometricObjects                  `xml:"GM03_2_1Comprehensive.Comprehensive.MD_GeometricObjects"`
	GM0321CoreCorereferenceSystemInfoMDMetadata                         GM0321CoreCorereferenceSystemInfoMDMetadata                         `xml:"GM03_2_1Core.Core.referenceSystemInfoMD_Metadata"`
	GM0321CoreCoreMDReferenceSystem                                     GM0321CoreCoreMDReferenceSystem                                     `xml:"GM03_2_1Core.Core.MD_ReferenceSystem"`
	GM0321ComprehensiveComprehensiveRSIdentifier                        GM0321ComprehensiveComprehensiveRSIdentifier                        `xml:"GM03_2_1Comprehensive.Comprehensive.RS_Identifier"`
	GM0321ComprehensiveComprehensiveMDDataIdentification                GM0321ComprehensiveComprehensiveMDDataIdentification                `xml:"GM03_2_1Comprehensive.Comprehensive.MD_DataIdentification"`
	GM0321ComprehensiveComprehensiveCICitation                          []GM0321ComprehensiveComprehensiveCICitation                        `xml:"GM03_2_1Comprehensive.Comprehensive.CI_Citation"`
	GM0321CoreCoreCIDate                                                []GM0321CoreCoreCIDate                                              `xml:"GM03_2_1Core.Core.CI_Date"`
	GM0321ComprehensiveComprehensiveCICitationidentifier                []GM0321ComprehensiveComprehensiveCICitationidentifier              `xml:"GM03_2_1Comprehensive.Comprehensive.CI_Citationidentifier"`
	GM0321CoreCoreMDIdentifier                                          []GM0321CoreCoreMDIdentifier                                        `xml:"GM03_2_1Core.Core.MD_Identifier"`
	GM0321CoreCoreMDIdentificationpointOfContact                        GM0321CoreCoreMDIdentificationpointOfContact                        `xml:"GM03_2_1Core.Core.MD_IdentificationpointOfContact"`
	GM0321CoreCoredescriptiveKeywordsMDIdentification                   []GM0321CoreCoredescriptiveKeywordsMDIdentification                 `xml:"GM03_2_1Core.Core.descriptiveKeywordsMD_Identification"`
	GM0321CoreCoreMDKeywords                                            []GM0321CoreCoreMDKeywords                                          `xml:"GM03_2_1Core.Core.MD_Keywords"`
	GM0321CoreCoreMDThesaurus                                           []GM0321CoreCoreMDThesaurus                                         `xml:"GM03_2_1Core.Core.MD_Thesaurus"`
	GM0321ComprehensiveComprehensiveresourceConstraintsMDIdentification GM0321ComprehensiveComprehensiveresourceConstraintsMDIdentification `xml:"GM03_2_1Comprehensive.Comprehensive.resourceConstraintsMD_Identification"`
	GM0321ComprehensiveComprehensiveMDLegalConstraints                  GM0321ComprehensiveComprehensiveMDLegalConstraints                  `xml:"GM03_2_1Comprehensive.Comprehensive.MD_LegalConstraints"`
	GM0321CoreCoreMDResolution                                          []GM0321CoreCoreMDResolution                                        `xml:"GM03_2_1Core.Core.MD_Resolution"`
	GM0321CoreCoreMDRepresentativeFraction                              []GM0321CoreCoreMDRepresentativeFraction                            `xml:"GM03_2_1Core.Core.MD_RepresentativeFraction"`
	GM0321CoreCoreEXExtent                                              GM0321CoreCoreEXExtent                                              `xml:"GM03_2_1Core.Core.EX_Extent"`
	GM0321CoreCoreEXExtentgeographicElement                             []GM0321CoreCoreEXExtentgeographicElement                           `xml:"GM03_2_1Core.Core.EX_ExtentgeographicElement"`
	GM0321CoreCoreEXGeographicBoundingBox                               GM0321CoreCoreEXGeographicBoundingBox                               `xml:"GM03_2_1Core.Core.EX_GeographicBoundingBox"`
	GM0321CoreCoreEXBoundingPolygon                                     GM0321CoreCoreEXBoundingPolygon                                     `xml:"GM03_2_1Core.Core.EX_BoundingPolygon"`
	GM0321CoreCoreDQDataQuality                                         GM0321CoreCoreDQDataQuality                                         `xml:"GM03_2_1Core.Core.DQ_DataQuality"`
	GM0321CoreCoreDQScope                                               GM0321CoreCoreDQScope                                               `xml:"GM03_2_1Core.Core.DQ_Scope"`
	GM0321CoreCoreLILineage                                             GM0321CoreCoreLILineage                                             `xml:"GM03_2_1Core.Core.LI_Lineage"`
	GM0321ComprehensiveComprehensiveMDMetadatalegislationInformation    []GM0321ComprehensiveComprehensiveMDMetadatalegislationInformation  `xml:"GM03_2_1Comprehensive.Comprehensive.MD_MetadatalegislationInformation"`
	GM0321ComprehensiveComprehensiveMDLegislation                       []GM0321ComprehensiveComprehensiveMDLegislation                     `xml:"GM03_2_1Comprehensive.Comprehensive.MD_Legislation"`
	GM0321ComprehensiveComprehensiveCISeries                            []GM0321ComprehensiveComprehensiveCISeries                          `xml:"GM03_2_1Comprehensive.Comprehensive.CI_Series"`
}

type GM0321CoreCoreMDMetadata struct {
	TID                  string           `xml:"TID,attr"`
	FileIdentifier       string           `xml:"fileIdentifier"`
	Language             Language         `xml:"language"`
	CharacterSet         CharacterSet     `xml:"characterSet"`
	DateStamp            string           `xml:"dateStamp"`
	MetadataStandardName string           `xml:"metadataStandardName"`
	HierarchyLevel       HierarchyLevel   `xml:"hierarchyLevel"`
	DistributionInfo     DistributionInfo `xml:"distributionInfo"`
}

type Language struct {
	CharData               string                   `xml:",chardata"`
	CodeISOLanguageCodeISO []CodeISOLanguageCodeISO `xml:"CodeISO.LanguageCodeISO_"`
}

type CharacterSet struct {
	CharData                         string                           `xml:",chardata"`
	GM0321CoreCoreMDCharacterSetCode GM0321CoreCoreMDCharacterSetCode `xml:"GM03_2_1Core.Core.MD_CharacterSetCode_"`
}

type HierarchyLevel struct {
	GM0321CoreCoreMDScopeCode GM0321CoreCoreMDScopeCode `xml:"GM03_2_1Core.Core.MD_ScopeCode_"`
}

type GM0321CoreCoreMDScopeCode struct {
	Value string `xml:"value"`
}

type DistributionInfo struct {
	REF string `xml:"REF,attr"`
}

type GM0321CoreCoreMDDistribution struct {
	TID string `xml:"TID,attr"`
}

type GM0321CoreCoreMDDistributiondistributionFormat struct {
	MDDistribution     MDDistribution     `xml:"MD_Distribution"`
	DistributionFormat DistributionFormat `xml:"distributionFormat"`
}

type MDDistribution struct {
	REF string `xml:"REF,attr"`
}

type DistributionFormat struct {
	REF string `xml:"REF,attr"`
}

type GM0321ComprehensiveComprehensiveMDFormat struct {
	TID     string  `xml:"TID,attr"`
	Name    Name    `xml:"name"`
	Version float64 `xml:"version"`
}

type Name struct {
	CharData                 string                   `xml:",chardata"`
	GM0321CoreCorePTFreeText GM0321CoreCorePTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type GM0321ComprehensiveComprehensiveMDDigitalTransferOptions struct {
	TID            string         `xml:"TID,attr"`
	MDDistribution MDDistribution `xml:"MD_Distribution"`
}

type GM0321CoreCoreCIOnlineResource struct {
	TID                      string                   `xml:"TID,attr"`
	Protocol                 string                   `xml:"protocol"`
	Description              Description              `xml:"description"`
	Name                     *Name                    `xml:"name"`
	Linkage                  Linkage                  `xml:"linkage"`
	MDDigitalTransferOptions MDDigitalTransferOptions `xml:"MD_DigitalTransferOptions"`
	Function                 *string                  `xml:"function"`
}

type Description struct {
	GM0321CoreCorePTFreeText GM0321CoreCorePTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type GM0321CoreCorePTFreeText struct {
	TextGroup TextGroup `xml:"textGroup"`
}

type TextGroup struct {
	GM0321CoreCorePTGroup []GM0321CoreCorePTGroup `xml:"GM03_2_1Core.Core.PT_Group"`
}

type GM0321CoreCorePTGroup struct {
	Language  Language `xml:"language"`
	PlainText string   `xml:"plainText"`
}

type Linkage struct {
	GM0321CoreCorePTFreeURL GM0321CoreCorePTFreeURL `xml:"GM03_2_1Core.Core.PT_FreeURL"`
}

type GM0321CoreCorePTFreeURL struct {
	URLGroup URLGroup `xml:"URLGroup"`
}

type URLGroup struct {
	GM0321CoreCorePTURLGroup []GM0321CoreCorePTURLGroup `xml:"GM03_2_1Core.Core.PT_URLGroup"`
}

type GM0321CoreCorePTURLGroup struct {
	Language Language `xml:"language"`
	PlainURL string   `xml:"plainURL"`
}

type MDDigitalTransferOptions struct {
	REF string `xml:"REF,attr"`
}

type GM0321CoreCoreMDMetadatacontact struct {
	Contact    Contact    `xml:"contact"`
	MDMetadata MDMetadata `xml:"MD_Metadata"`
	Role       Role       `xml:"role"`
}

type Contact struct {
	REF string `xml:"REF,attr"`
}

type MDMetadata struct {
	REF string `xml:"REF,attr"`
}

type Role struct {
	GM0321CoreCoreCIRoleCode GM0321CoreCoreCIRoleCode `xml:"GM03_2_1Core.Core.CI_RoleCode_"`
}

type GM0321CoreCoreCIRoleCode struct {
	Value string `xml:"value"`
}

type GM0321CoreCoreCIResponsibleParty struct {
	TID                     string                  `xml:"TID,attr"`
	IndividualFirstName     *string                 `xml:"individualFirstName"`
	IndividualLastName      string                  `xml:"individualLastName"`
	ElectronicalMailAddress ElectronicalMailAddress `xml:"electronicalMailAddress"`
	OrganisationName        OrganisationName        `xml:"organisationName"`
	PositionName            PositionName            `xml:"positionName"`
	OrganisationAcronym     OrganisationAcronym     `xml:"organisationAcronym"`
	Linkage                 Linkage                 `xml:"linkage"`
	Address                 Address                 `xml:"address"`
	ContactInfo             ContactInfo             `xml:"contactInfo"`
}

type ElectronicalMailAddress struct {
	GM0321CoreCoreURL GM0321CoreCoreURL `xml:"GM03_2_1Core.Core.URL_"`
}

type GM0321CoreCoreURL struct {
	Value string `xml:"value"`
}

type OrganisationName struct {
	GM0321CoreCorePTFreeText GM0321CoreCorePTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type PositionName struct {
	GM0321CoreCorePTFreeText GM0321CoreCorePTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type OrganisationAcronym struct {
	GM0321CoreCorePTFreeText GM0321CoreCorePTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type Address struct {
	REF string `xml:"REF,attr"`
}

type ContactInfo struct {
	REF string `xml:"REF,attr"`
}

type GM0321CoreCoreCIAddress struct {
	TID        string  `xml:"TID,attr"`
	PostalCode string  `xml:"postalCode"`
	City       string  `xml:"city"`
	Country    Country `xml:"country"`
}

type Country struct {
	CharData              string                `xml:",chardata"`
	CodeISOCountryCodeISO CodeISOCountryCodeISO `xml:"CodeISO.CountryCodeISO_"`
}

type GM0321CoreCoreCIContact struct {
	TID string `xml:"TID,attr"`
}

type GM0321CoreCoreCITelephone struct {
	TID                string             `xml:"TID,attr"`
	Number             string             `xml:"number"`
	NumberType         string             `xml:"numberType"`
	CIResponsibleParty CIResponsibleParty `xml:"CI_ResponsibleParty"`
}

type CIResponsibleParty struct {
	REF string `xml:"REF,attr"`
}

type GM0321ComprehensiveComprehensiveMDVectorSpatialRepresentation struct {
	Gml320     string     `xml:"gml320,attr"`
	TID        string     `xml:"TID,attr"`
	MDMetadata MDMetadata `xml:"MD_Metadata"`
}

type GM0321ComprehensiveComprehensiveMDGeometricObjects struct {
	TID                           string                        `xml:"TID,attr"`
	GeometricObjectType           string                        `xml:"geometricObjectType"`
	MDVectorSpatialRepresentation MDVectorSpatialRepresentation `xml:"MD_VectorSpatialRepresentation"`
}

type MDVectorSpatialRepresentation struct {
	REF string `xml:"REF,attr"`
}

type GM0321CoreCorereferenceSystemInfoMDMetadata struct {
	ReferenceSystemInfo ReferenceSystemInfo `xml:"referenceSystemInfo"`
	MDMetadata          MDMetadata          `xml:"MD_Metadata"`
}

type ReferenceSystemInfo struct {
	REF string `xml:"REF,attr"`
}

type GM0321CoreCoreMDReferenceSystem struct {
	TID                       string                    `xml:"TID,attr"`
	ReferenceSystemIdentifier ReferenceSystemIdentifier `xml:"referenceSystemIdentifier"`
}

type ReferenceSystemIdentifier struct {
	REF string `xml:"REF,attr"`
}

type GM0321ComprehensiveComprehensiveRSIdentifier struct {
	TID  string `xml:"TID,attr"`
	Code Code   `xml:"code"`
}

type Code struct {
	GM0321CoreCorePTFreeText GM0321CoreCorePTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type GM0321ComprehensiveComprehensiveMDDataIdentification struct {
	TID                       string                    `xml:"TID,attr"`
	Status                    Status                    `xml:"status"`
	Abstract                  Abstract                  `xml:"abstract"`
	MDMetadata                MDMetadata                `xml:"MD_Metadata"`
	Citation                  Citation                  `xml:"citation"`
	SpatialRepresentationType SpatialRepresentationType `xml:"spatialRepresentationType"`
	Language                  Language                  `xml:"language"`
	CharacterSet              CharacterSet              `xml:"characterSet"`
	TopicCategory             TopicCategory             `xml:"topicCategory"`
}

type Status struct {
	GM0321CoreCoreMDProgressCode GM0321CoreCoreMDProgressCode `xml:"GM03_2_1Core.Core.MD_ProgressCode_"`
}

type GM0321CoreCoreMDProgressCode struct {
	Value string `xml:"value"`
}

type Abstract struct {
	GM0321CoreCorePTFreeText GM0321CoreCorePTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type Citation struct {
	REF string `xml:"REF,attr"`
}

type SpatialRepresentationType struct {
	GM0321CoreCoreMDSpatialRepresentationTypeCode GM0321CoreCoreMDSpatialRepresentationTypeCode `xml:"GM03_2_1Core.Core.MD_SpatialRepresentationTypeCode_"`
}

type GM0321CoreCoreMDSpatialRepresentationTypeCode struct {
	Value string `xml:"value"`
}

type CodeISOLanguageCodeISO struct {
	Value string `xml:"value"`
}

type GM0321CoreCoreMDCharacterSetCode struct {
	Value string `xml:"value"`
}

type TopicCategory struct {
	GM0321CoreCoreMDTopicCategoryCode GM0321CoreCoreMDTopicCategoryCode `xml:"GM03_2_1Core.Core.MD_TopicCategoryCode_"`
}

type GM0321CoreCoreMDTopicCategoryCode struct {
	Value string `xml:"value"`
}

type GM0321ComprehensiveComprehensiveCICitation struct {
	TID                  string                `xml:"TID,attr"`
	Title                Title                 `xml:"title"`
	AlternateTitle       *AlternateTitle       `xml:"alternateTitle"`
	OtherCitationDetails *OtherCitationDetails `xml:"otherCitationDetails"`
	Series               Series                `xml:"series"`
}

type Title struct {
	REF                      *string                   `xml:"REF,attr"`
	GM0321CoreCorePTFreeText *GM0321CoreCorePTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type AlternateTitle struct {
	GM0321CoreCorePTFreeText GM0321CoreCorePTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type GM0321CoreCoreCIDate struct {
	TID        string     `xml:"TID,attr"`
	Date       string     `xml:"date"`
	DateType   string     `xml:"dateType"`
	CICitation CICitation `xml:"CI_Citation"`
}

type CICitation struct {
	REF string `xml:"REF,attr"`
}

type GM0321ComprehensiveComprehensiveCICitationidentifier struct {
	Identifier Identifier `xml:"identifier"`
	CICitation CICitation `xml:"CI_Citation"`
}

type Identifier struct {
	REF string `xml:"REF,attr"`
}

type GM0321CoreCoreMDIdentifier struct {
	TID  string `xml:"TID,attr"`
	Code Code   `xml:"code"`
}

type GM0321CoreCoreMDIdentificationpointOfContact struct {
	PointOfContact   PointOfContact   `xml:"pointOfContact"`
	MDIdentification MDIdentification `xml:"MD_Identification"`
	Role             Role             `xml:"role"`
}

type PointOfContact struct {
	REF string `xml:"REF,attr"`
}

type MDIdentification struct {
	REF string `xml:"REF,attr"`
}

type GM0321CoreCoredescriptiveKeywordsMDIdentification struct {
	DescriptiveKeywords DescriptiveKeywords `xml:"descriptiveKeywords"`
	MDIdentification    MDIdentification    `xml:"MD_Identification"`
}

type DescriptiveKeywords struct {
	REF string `xml:"REF,attr"`
}

type GM0321CoreCoreMDKeywords struct {
	TID       string    `xml:"TID,attr"`
	Keyword   Keyword   `xml:"keyword"`
	Thesaurus Thesaurus `xml:"thesaurus"`
}

type Keyword struct {
	GM0321CoreCorePTFreeText []GM0321CoreCorePTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type Thesaurus struct {
	REF string `xml:"REF,attr"`
}

type GM0321CoreCoreMDThesaurus struct {
	TID      string   `xml:"TID,attr"`
	Citation Citation `xml:"citation"`
}

type GM0321ComprehensiveComprehensiveresourceConstraintsMDIdentification struct {
	ResourceConstraints ResourceConstraints `xml:"resourceConstraints"`
	MDIdentification    MDIdentification    `xml:"MD_Identification"`
}

type ResourceConstraints struct {
	REF string `xml:"REF,attr"`
}

type GM0321ComprehensiveComprehensiveMDLegalConstraints struct {
	TID              string           `xml:"TID,attr"`
	UseConstraints   UseConstraints   `xml:"useConstraints"`
	OtherConstraints OtherConstraints `xml:"otherConstraints"`
}

type UseConstraints struct {
	GM0321ComprehensiveComprehensiveMDRestrictionCode GM0321ComprehensiveComprehensiveMDRestrictionCode `xml:"GM03_2_1Comprehensive.Comprehensive.MD_RestrictionCode_"`
}

type GM0321ComprehensiveComprehensiveMDRestrictionCode struct {
	Value string `xml:"value"`
}

type OtherConstraints struct {
	GM0321CoreCorePTFreeText []GM0321CoreCorePTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type GM0321CoreCoreMDResolution struct {
	TID                  string               `xml:"TID,attr"`
	MDDataIdentification MDDataIdentification `xml:"MD_DataIdentification"`
	EquivalentScale      EquivalentScale      `xml:"equivalentScale"`
}

type MDDataIdentification struct {
	REF string `xml:"REF,attr"`
}

type EquivalentScale struct {
	REF string `xml:"REF,attr"`
}

type GM0321CoreCoreMDRepresentativeFraction struct {
	TID         string `xml:"TID,attr"`
	Denominator int    `xml:"denominator"`
}

type GM0321CoreCoreEXExtent struct {
	TID                  string               `xml:"TID,attr"`
	Description          Description          `xml:"description"`
	MDDataIdentification MDDataIdentification `xml:"MD_DataIdentification"`
}

type GM0321CoreCoreEXExtentgeographicElement struct {
	EXExtent          EXExtent          `xml:"EX_Extent"`
	GeographicElement GeographicElement `xml:"geographicElement"`
}

type EXExtent struct {
	REF string `xml:"REF,attr"`
}

type GeographicElement struct {
	REF string `xml:"REF,attr"`
}

type GM0321CoreCoreEXGeographicBoundingBox struct {
	TID                string  `xml:"TID,attr"`
	NorthBoundLatitude float64 `xml:"northBoundLatitude"`
	SouthBoundLatitude float64 `xml:"southBoundLatitude"`
	EastBoundLongitude float64 `xml:"eastBoundLongitude"`
	WestBoundLongitude float64 `xml:"westBoundLongitude"`
}

type GM0321CoreCoreEXBoundingPolygon struct {
	TID     string  `xml:"TID,attr"`
	Polygon Polygon `xml:"polygon"`
}

type Polygon struct {
	Surface Surface `xml:"SURFACE"`
}

type Surface struct {
	Boundary Boundary `xml:"BOUNDARY"`
}

type Boundary struct {
	PolyLine PolyLine `xml:"POLYLINE"`
}

type PolyLine struct {
	Coord []Coord `xml:"COORD"`
}

type Coord struct {
	C1 float64 `xml:"C1"`
	C2 float64 `xml:"C2"`
}

type GM0321CoreCoreDQDataQuality struct {
	Gml320     string     `xml:"gml320,attr"`
	TID        string     `xml:"TID,attr"`
	MDMetadata MDMetadata `xml:"MD_Metadata"`
}

type GM0321CoreCoreDQScope struct {
	TID           string        `xml:"TID,attr"`
	Level         string        `xml:"level"`
	DQDataQuality DQDataQuality `xml:"DQ_DataQuality"`
}

type DQDataQuality struct {
	REF string `xml:"REF,attr"`
}

type GM0321CoreCoreLILineage struct {
	TID           string        `xml:"TID,attr"`
	Statement     Statement     `xml:"statement"`
	DQDataQuality DQDataQuality `xml:"DQ_DataQuality"`
}

type Statement struct {
	GM0321CoreCorePTFreeText GM0321CoreCorePTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type GM0321ComprehensiveComprehensiveMDMetadatalegislationInformation struct {
	MDMetadata             MDMetadata             `xml:"MD_Metadata"`
	LegislationInformation LegislationInformation `xml:"legislationInformation"`
}

type LegislationInformation struct {
	REF string `xml:"REF,attr"`
}

type GM0321ComprehensiveComprehensiveMDLegislation struct {
	TID               string            `xml:"TID,attr"`
	Country           Country           `xml:"country"`
	Language          Language          `xml:"language"`
	LegislationType   string            `xml:"legislationType"`
	InternalReference InternalReference `xml:"internalReference"`
	Title             Title             `xml:"title"`
}

type CodeISOCountryCodeISO struct {
	Value string `xml:"value"`
}

type InternalReference struct {
	GM0321CoreCoreCharacterString GM0321CoreCoreCharacterString `xml:"GM03_2_1Core.Core.CharacterString_"`
}

type GM0321CoreCoreCharacterString struct {
	Value string `xml:"value"`
}

type OtherCitationDetails struct {
	GM0321CoreCorePTFreeText GM0321CoreCorePTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type Series struct {
	REF string `xml:"REF,attr"`
}

type GM0321ComprehensiveComprehensiveCISeries struct {
	TID  string `xml:"TID,attr"`
	Name Name   `xml:"name"`
}
