// This file is automatically generated. DO NOT EDIT.

package interlis

type Transfer struct {
	HeaderSection HeaderSection `xml:"HEADERSECTION"`
	DataSection   DataSection   `xml:"DATASECTION"`
}

type HeaderSection struct {
	Sender  string   `xml:"SENDER,attr"`
	Version float64  `xml:"VERSION,attr"`
	Models  struct{} `xml:"MODELS"`
}

type DataSection struct {
	GM03_2_1Comprehensive_Comprehensive GM03_2_1Comprehensive_Comprehensive `xml:"GM03_2_1Comprehensive.Comprehensive"`
}

type GM03_2_1Comprehensive_Comprehensive struct {
	BID                                                                     string                                                                  `xml:"BID,attr"`
	GM03_2_1Core_Core_MDMetadata                                            GM03_2_1Core_Core_MDMetadata                                            `xml:"GM03_2_1Core.Core.MD_Metadata"`
	GM03_2_1Core_Core_MDDistribution                                        GM03_2_1Core_Core_MDDistribution                                        `xml:"GM03_2_1Core.Core.MD_Distribution"`
	GM03_2_1Core_Core_MDDistributiondistributionFormat                      GM03_2_1Core_Core_MDDistributiondistributionFormat                      `xml:"GM03_2_1Core.Core.MD_DistributiondistributionFormat"`
	GM03_2_1Comprehensive_Comprehensive_MDFormat                            GM03_2_1Comprehensive_Comprehensive_MDFormat                            `xml:"GM03_2_1Comprehensive.Comprehensive.MD_Format"`
	GM03_2_1Comprehensive_Comprehensive_MDDigitalTransferOptions            GM03_2_1Comprehensive_Comprehensive_MDDigitalTransferOptions            `xml:"GM03_2_1Comprehensive.Comprehensive.MD_DigitalTransferOptions"`
	GM03_2_1Core_Core_CIOnlineResource                                      []GM03_2_1Core_Core_CIOnlineResource                                    `xml:"GM03_2_1Core.Core.CI_OnlineResource"`
	GM03_2_1Core_Core_MDMetadatacontact                                     GM03_2_1Core_Core_MDMetadatacontact                                     `xml:"GM03_2_1Core.Core.MD_Metadatacontact"`
	GM03_2_1Core_Core_CIResponsibleParty                                    []GM03_2_1Core_Core_CIResponsibleParty                                  `xml:"GM03_2_1Core.Core.CI_ResponsibleParty"`
	GM03_2_1Core_Core_CIAddress                                             []GM03_2_1Core_Core_CIAddress                                           `xml:"GM03_2_1Core.Core.CI_Address"`
	GM03_2_1Core_Core_CIContact                                             []GM03_2_1Core_Core_CIContact                                           `xml:"GM03_2_1Core.Core.CI_Contact"`
	GM03_2_1Core_Core_CITelephone                                           []GM03_2_1Core_Core_CITelephone                                         `xml:"GM03_2_1Core.Core.CI_Telephone"`
	GM03_2_1Comprehensive_Comprehensive_MDVectorSpatialRepresentation       GM03_2_1Comprehensive_Comprehensive_MDVectorSpatialRepresentation       `xml:"GM03_2_1Comprehensive.Comprehensive.MD_VectorSpatialRepresentation"`
	GM03_2_1Comprehensive_Comprehensive_MDGeometricObjects                  GM03_2_1Comprehensive_Comprehensive_MDGeometricObjects                  `xml:"GM03_2_1Comprehensive.Comprehensive.MD_GeometricObjects"`
	GM03_2_1Core_Core_referenceSystemInfoMDMetadata                         GM03_2_1Core_Core_referenceSystemInfoMDMetadata                         `xml:"GM03_2_1Core.Core.referenceSystemInfoMD_Metadata"`
	GM03_2_1Core_Core_MDReferenceSystem                                     GM03_2_1Core_Core_MDReferenceSystem                                     `xml:"GM03_2_1Core.Core.MD_ReferenceSystem"`
	GM03_2_1Comprehensive_Comprehensive_RSIdentifier                        GM03_2_1Comprehensive_Comprehensive_RSIdentifier                        `xml:"GM03_2_1Comprehensive.Comprehensive.RS_Identifier"`
	GM03_2_1Comprehensive_Comprehensive_MDDataIdentification                GM03_2_1Comprehensive_Comprehensive_MDDataIdentification                `xml:"GM03_2_1Comprehensive.Comprehensive.MD_DataIdentification"`
	GM03_2_1Comprehensive_Comprehensive_CICitation                          []GM03_2_1Comprehensive_Comprehensive_CICitation                        `xml:"GM03_2_1Comprehensive.Comprehensive.CI_Citation"`
	GM03_2_1Core_Core_CIDate                                                []GM03_2_1Core_Core_CIDate                                              `xml:"GM03_2_1Core.Core.CI_Date"`
	GM03_2_1Comprehensive_Comprehensive_CICitationidentifier                []GM03_2_1Comprehensive_Comprehensive_CICitationidentifier              `xml:"GM03_2_1Comprehensive.Comprehensive.CI_Citationidentifier"`
	GM03_2_1Core_Core_MDIdentifier                                          []GM03_2_1Core_Core_MDIdentifier                                        `xml:"GM03_2_1Core.Core.MD_Identifier"`
	GM03_2_1Core_Core_MDIdentificationpointOfContact                        GM03_2_1Core_Core_MDIdentificationpointOfContact                        `xml:"GM03_2_1Core.Core.MD_IdentificationpointOfContact"`
	GM03_2_1Core_Core_descriptiveKeywordsMDIdentification                   []GM03_2_1Core_Core_descriptiveKeywordsMDIdentification                 `xml:"GM03_2_1Core.Core.descriptiveKeywordsMD_Identification"`
	GM03_2_1Core_Core_MDKeywords                                            []GM03_2_1Core_Core_MDKeywords                                          `xml:"GM03_2_1Core.Core.MD_Keywords"`
	GM03_2_1Core_Core_MDThesaurus                                           []GM03_2_1Core_Core_MDThesaurus                                         `xml:"GM03_2_1Core.Core.MD_Thesaurus"`
	GM03_2_1Comprehensive_Comprehensive_resourceConstraintsMDIdentification GM03_2_1Comprehensive_Comprehensive_resourceConstraintsMDIdentification `xml:"GM03_2_1Comprehensive.Comprehensive.resourceConstraintsMD_Identification"`
	GM03_2_1Comprehensive_Comprehensive_MDLegalConstraints                  GM03_2_1Comprehensive_Comprehensive_MDLegalConstraints                  `xml:"GM03_2_1Comprehensive.Comprehensive.MD_LegalConstraints"`
	GM03_2_1Core_Core_MDResolution                                          []GM03_2_1Core_Core_MDResolution                                        `xml:"GM03_2_1Core.Core.MD_Resolution"`
	GM03_2_1Core_Core_MDRepresentativeFraction                              []GM03_2_1Core_Core_MDRepresentativeFraction                            `xml:"GM03_2_1Core.Core.MD_RepresentativeFraction"`
	GM03_2_1Core_Core_EXExtent                                              GM03_2_1Core_Core_EXExtent                                              `xml:"GM03_2_1Core.Core.EX_Extent"`
	GM03_2_1Core_Core_EXExtentgeographicElement                             []GM03_2_1Core_Core_EXExtentgeographicElement                           `xml:"GM03_2_1Core.Core.EX_ExtentgeographicElement"`
	GM03_2_1Core_Core_EXGeographicBoundingBox                               GM03_2_1Core_Core_EXGeographicBoundingBox                               `xml:"GM03_2_1Core.Core.EX_GeographicBoundingBox"`
	GM03_2_1Core_Core_EXBoundingPolygon                                     GM03_2_1Core_Core_EXBoundingPolygon                                     `xml:"GM03_2_1Core.Core.EX_BoundingPolygon"`
	GM03_2_1Core_Core_DQDataQuality                                         GM03_2_1Core_Core_DQDataQuality                                         `xml:"GM03_2_1Core.Core.DQ_DataQuality"`
	GM03_2_1Core_Core_DQScope                                               GM03_2_1Core_Core_DQScope                                               `xml:"GM03_2_1Core.Core.DQ_Scope"`
	GM03_2_1Core_Core_LILineage                                             GM03_2_1Core_Core_LILineage                                             `xml:"GM03_2_1Core.Core.LI_Lineage"`
	GM03_2_1Comprehensive_Comprehensive_MDMetadatalegislationInformation    []GM03_2_1Comprehensive_Comprehensive_MDMetadatalegislationInformation  `xml:"GM03_2_1Comprehensive.Comprehensive.MD_MetadatalegislationInformation"`
	GM03_2_1Comprehensive_Comprehensive_MDLegislation                       []GM03_2_1Comprehensive_Comprehensive_MDLegislation                     `xml:"GM03_2_1Comprehensive.Comprehensive.MD_Legislation"`
	GM03_2_1Comprehensive_Comprehensive_CISeries                            []GM03_2_1Comprehensive_Comprehensive_CISeries                          `xml:"GM03_2_1Comprehensive.Comprehensive.CI_Series"`
}

type GM03_2_1Core_Core_MDMetadata struct {
	TID                  string           `xml:"TID,attr"`
	FileIdentifier       string           `xml:"fileIdentifier"`
	Language             Language         `xml:"language"`
	CharacterSet         CharacterSet     `xml:"characterSet"`
	DateStamp            string           `xml:"dateStamp"`
	MetadataStandardName string           `xml:"metadataStandardName"`
	HierarchyLevel       HierarchyLevel   `xml:"hierarchyLevel"`
	DistributionInfo     DistributionInfo `xml:"distributionInfo"`
}

type Language struct {
	CharData                 string                     `xml:",chardata"`
	CodeISO_LanguageCodeISO_ []CodeISO_LanguageCodeISO_ `xml:"CodeISO.LanguageCodeISO_"`
}

type CharacterSet struct {
	CharData                              string                                `xml:",chardata"`
	GM03_2_1Core_Core_MDCharacterSetCode_ GM03_2_1Core_Core_MDCharacterSetCode_ `xml:"GM03_2_1Core.Core.MD_CharacterSetCode_"`
}

type HierarchyLevel struct {
	GM03_2_1Core_Core_MDScopeCode_ GM03_2_1Core_Core_MDScopeCode_ `xml:"GM03_2_1Core.Core.MD_ScopeCode_"`
}

type GM03_2_1Core_Core_MDScopeCode_ struct {
	Value string `xml:"value"`
}

type DistributionInfo struct {
	REF string `xml:"REF,attr"`
}

type GM03_2_1Core_Core_MDDistribution struct {
	TID string `xml:"TID,attr"`
}

type GM03_2_1Core_Core_MDDistributiondistributionFormat struct {
	MDDistribution     MDDistribution     `xml:"MD_Distribution"`
	DistributionFormat DistributionFormat `xml:"distributionFormat"`
}

type MDDistribution struct {
	REF string `xml:"REF,attr"`
}

type DistributionFormat struct {
	REF string `xml:"REF,attr"`
}

type GM03_2_1Comprehensive_Comprehensive_MDFormat struct {
	TID     string  `xml:"TID,attr"`
	Name    Name    `xml:"name"`
	Version float64 `xml:"version"`
}

type Name struct {
	CharData                     string                       `xml:",chardata"`
	GM03_2_1Core_Core_PTFreeText GM03_2_1Core_Core_PTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type GM03_2_1Comprehensive_Comprehensive_MDDigitalTransferOptions struct {
	TID            string         `xml:"TID,attr"`
	MDDistribution MDDistribution `xml:"MD_Distribution"`
}

type GM03_2_1Core_Core_CIOnlineResource struct {
	TID                      string                   `xml:"TID,attr"`
	Protocol                 string                   `xml:"protocol"`
	Description              Description              `xml:"description"`
	Name                     *Name                    `xml:"name"`
	Linkage                  Linkage                  `xml:"linkage"`
	MDDigitalTransferOptions MDDigitalTransferOptions `xml:"MD_DigitalTransferOptions"`
	Function                 *string                  `xml:"function"`
}

type Description struct {
	GM03_2_1Core_Core_PTFreeText GM03_2_1Core_Core_PTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type GM03_2_1Core_Core_PTFreeText struct {
	TextGroup TextGroup `xml:"textGroup"`
}

type TextGroup struct {
	GM03_2_1Core_Core_PTGroup []GM03_2_1Core_Core_PTGroup `xml:"GM03_2_1Core.Core.PT_Group"`
}

type GM03_2_1Core_Core_PTGroup struct {
	Language  Language `xml:"language"`
	PlainText string   `xml:"plainText"`
}

type Linkage struct {
	GM03_2_1Core_Core_PTFreeURL GM03_2_1Core_Core_PTFreeURL `xml:"GM03_2_1Core.Core.PT_FreeURL"`
}

type GM03_2_1Core_Core_PTFreeURL struct {
	URLGroup URLGroup `xml:"URLGroup"`
}

type URLGroup struct {
	GM03_2_1Core_Core_PTURLGroup []GM03_2_1Core_Core_PTURLGroup `xml:"GM03_2_1Core.Core.PT_URLGroup"`
}

type GM03_2_1Core_Core_PTURLGroup struct {
	Language Language `xml:"language"`
	PlainURL string   `xml:"plainURL"`
}

type MDDigitalTransferOptions struct {
	REF string `xml:"REF,attr"`
}

type GM03_2_1Core_Core_MDMetadatacontact struct {
	Contact    Contact    `xml:"contact"`
	MDMetadata MDMetadata `xml:"MD_Metadata"`
	Role       Role       `xml:"role"`
}

type Contact struct {
	REF string `xml:"REF,attr"`
}

type MDMetadata struct {
	REF string `xml:"REF,attr"`
}

type Role struct {
	GM03_2_1Core_Core_CIRoleCode_ GM03_2_1Core_Core_CIRoleCode_ `xml:"GM03_2_1Core.Core.CI_RoleCode_"`
}

type GM03_2_1Core_Core_CIRoleCode_ struct {
	Value string `xml:"value"`
}

type GM03_2_1Core_Core_CIResponsibleParty struct {
	TID                     string                  `xml:"TID,attr"`
	IndividualFirstName     *string                 `xml:"individualFirstName"`
	IndividualLastName      string                  `xml:"individualLastName"`
	ElectronicalMailAddress ElectronicalMailAddress `xml:"electronicalMailAddress"`
	OrganisationName        OrganisationName        `xml:"organisationName"`
	PositionName            PositionName            `xml:"positionName"`
	OrganisationAcronym     OrganisationAcronym     `xml:"organisationAcronym"`
	Linkage                 Linkage                 `xml:"linkage"`
	Address                 Address                 `xml:"address"`
	ContactInfo             ContactInfo             `xml:"contactInfo"`
}

type ElectronicalMailAddress struct {
	GM03_2_1Core_Core_URL_ GM03_2_1Core_Core_URL_ `xml:"GM03_2_1Core.Core.URL_"`
}

type GM03_2_1Core_Core_URL_ struct {
	Value string `xml:"value"`
}

type OrganisationName struct {
	GM03_2_1Core_Core_PTFreeText GM03_2_1Core_Core_PTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type PositionName struct {
	GM03_2_1Core_Core_PTFreeText GM03_2_1Core_Core_PTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type OrganisationAcronym struct {
	GM03_2_1Core_Core_PTFreeText GM03_2_1Core_Core_PTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type Address struct {
	REF string `xml:"REF,attr"`
}

type ContactInfo struct {
	REF string `xml:"REF,attr"`
}

type GM03_2_1Core_Core_CIAddress struct {
	TID        string  `xml:"TID,attr"`
	PostalCode string  `xml:"postalCode"`
	City       string  `xml:"city"`
	Country    Country `xml:"country"`
}

type Country struct {
	CharData                string                  `xml:",chardata"`
	CodeISO_CountryCodeISO_ CodeISO_CountryCodeISO_ `xml:"CodeISO.CountryCodeISO_"`
}

type GM03_2_1Core_Core_CIContact struct {
	TID string `xml:"TID,attr"`
}

type GM03_2_1Core_Core_CITelephone struct {
	TID                string             `xml:"TID,attr"`
	Number             string             `xml:"number"`
	NumberType         string             `xml:"numberType"`
	CIResponsibleParty CIResponsibleParty `xml:"CI_ResponsibleParty"`
}

type CIResponsibleParty struct {
	REF string `xml:"REF,attr"`
}

type GM03_2_1Comprehensive_Comprehensive_MDVectorSpatialRepresentation struct {
	Gml320     string     `xml:"gml320,attr"`
	TID        string     `xml:"TID,attr"`
	MDMetadata MDMetadata `xml:"MD_Metadata"`
}

type GM03_2_1Comprehensive_Comprehensive_MDGeometricObjects struct {
	TID                           string                        `xml:"TID,attr"`
	GeometricObjectType           string                        `xml:"geometricObjectType"`
	MDVectorSpatialRepresentation MDVectorSpatialRepresentation `xml:"MD_VectorSpatialRepresentation"`
}

type MDVectorSpatialRepresentation struct {
	REF string `xml:"REF,attr"`
}

type GM03_2_1Core_Core_referenceSystemInfoMDMetadata struct {
	ReferenceSystemInfo ReferenceSystemInfo `xml:"referenceSystemInfo"`
	MDMetadata          MDMetadata          `xml:"MD_Metadata"`
}

type ReferenceSystemInfo struct {
	REF string `xml:"REF,attr"`
}

type GM03_2_1Core_Core_MDReferenceSystem struct {
	TID                       string                    `xml:"TID,attr"`
	ReferenceSystemIdentifier ReferenceSystemIdentifier `xml:"referenceSystemIdentifier"`
}

type ReferenceSystemIdentifier struct {
	REF string `xml:"REF,attr"`
}

type GM03_2_1Comprehensive_Comprehensive_RSIdentifier struct {
	TID  string `xml:"TID,attr"`
	Code Code   `xml:"code"`
}

type Code struct {
	GM03_2_1Core_Core_PTFreeText GM03_2_1Core_Core_PTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type GM03_2_1Comprehensive_Comprehensive_MDDataIdentification struct {
	TID                       string                    `xml:"TID,attr"`
	Status                    Status                    `xml:"status"`
	Abstract                  Abstract                  `xml:"abstract"`
	MDMetadata                MDMetadata                `xml:"MD_Metadata"`
	Citation                  Citation                  `xml:"citation"`
	SpatialRepresentationType SpatialRepresentationType `xml:"spatialRepresentationType"`
	Language                  Language                  `xml:"language"`
	CharacterSet              CharacterSet              `xml:"characterSet"`
	TopicCategory             TopicCategory             `xml:"topicCategory"`
}

type Status struct {
	GM03_2_1Core_Core_MDProgressCode_ GM03_2_1Core_Core_MDProgressCode_ `xml:"GM03_2_1Core.Core.MD_ProgressCode_"`
}

type GM03_2_1Core_Core_MDProgressCode_ struct {
	Value string `xml:"value"`
}

type Abstract struct {
	GM03_2_1Core_Core_PTFreeText GM03_2_1Core_Core_PTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type Citation struct {
	REF string `xml:"REF,attr"`
}

type SpatialRepresentationType struct {
	GM03_2_1Core_Core_MDSpatialRepresentationTypeCode_ GM03_2_1Core_Core_MDSpatialRepresentationTypeCode_ `xml:"GM03_2_1Core.Core.MD_SpatialRepresentationTypeCode_"`
}

type GM03_2_1Core_Core_MDSpatialRepresentationTypeCode_ struct {
	Value string `xml:"value"`
}

type CodeISO_LanguageCodeISO_ struct {
	Value string `xml:"value"`
}

type GM03_2_1Core_Core_MDCharacterSetCode_ struct {
	Value string `xml:"value"`
}

type TopicCategory struct {
	GM03_2_1Core_Core_MDTopicCategoryCode_ GM03_2_1Core_Core_MDTopicCategoryCode_ `xml:"GM03_2_1Core.Core.MD_TopicCategoryCode_"`
}

type GM03_2_1Core_Core_MDTopicCategoryCode_ struct {
	Value string `xml:"value"`
}

type GM03_2_1Comprehensive_Comprehensive_CICitation struct {
	TID                  string                `xml:"TID,attr"`
	Title                Title                 `xml:"title"`
	AlternateTitle       *AlternateTitle       `xml:"alternateTitle"`
	OtherCitationDetails *OtherCitationDetails `xml:"otherCitationDetails"`
	Series               Series                `xml:"series"`
}

type Title struct {
	REF                          *string                       `xml:"REF,attr"`
	GM03_2_1Core_Core_PTFreeText *GM03_2_1Core_Core_PTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type AlternateTitle struct {
	GM03_2_1Core_Core_PTFreeText GM03_2_1Core_Core_PTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type GM03_2_1Core_Core_CIDate struct {
	TID        string     `xml:"TID,attr"`
	Date       string     `xml:"date"`
	DateType   string     `xml:"dateType"`
	CICitation CICitation `xml:"CI_Citation"`
}

type CICitation struct {
	REF string `xml:"REF,attr"`
}

type GM03_2_1Comprehensive_Comprehensive_CICitationidentifier struct {
	Identifier Identifier `xml:"identifier"`
	CICitation CICitation `xml:"CI_Citation"`
}

type Identifier struct {
	REF string `xml:"REF,attr"`
}

type GM03_2_1Core_Core_MDIdentifier struct {
	TID  string `xml:"TID,attr"`
	Code Code   `xml:"code"`
}

type GM03_2_1Core_Core_MDIdentificationpointOfContact struct {
	PointOfContact   PointOfContact   `xml:"pointOfContact"`
	MDIdentification MDIdentification `xml:"MD_Identification"`
	Role             Role             `xml:"role"`
}

type PointOfContact struct {
	REF string `xml:"REF,attr"`
}

type MDIdentification struct {
	REF string `xml:"REF,attr"`
}

type GM03_2_1Core_Core_descriptiveKeywordsMDIdentification struct {
	DescriptiveKeywords DescriptiveKeywords `xml:"descriptiveKeywords"`
	MDIdentification    MDIdentification    `xml:"MD_Identification"`
}

type DescriptiveKeywords struct {
	REF string `xml:"REF,attr"`
}

type GM03_2_1Core_Core_MDKeywords struct {
	TID       string    `xml:"TID,attr"`
	Keyword   Keyword   `xml:"keyword"`
	Thesaurus Thesaurus `xml:"thesaurus"`
}

type Keyword struct {
	GM03_2_1Core_Core_PTFreeText []GM03_2_1Core_Core_PTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type Thesaurus struct {
	REF string `xml:"REF,attr"`
}

type GM03_2_1Core_Core_MDThesaurus struct {
	TID      string   `xml:"TID,attr"`
	Citation Citation `xml:"citation"`
}

type GM03_2_1Comprehensive_Comprehensive_resourceConstraintsMDIdentification struct {
	ResourceConstraints ResourceConstraints `xml:"resourceConstraints"`
	MDIdentification    MDIdentification    `xml:"MD_Identification"`
}

type ResourceConstraints struct {
	REF string `xml:"REF,attr"`
}

type GM03_2_1Comprehensive_Comprehensive_MDLegalConstraints struct {
	TID              string           `xml:"TID,attr"`
	UseConstraints   UseConstraints   `xml:"useConstraints"`
	OtherConstraints OtherConstraints `xml:"otherConstraints"`
}

type UseConstraints struct {
	GM03_2_1Comprehensive_Comprehensive_MDRestrictionCode_ GM03_2_1Comprehensive_Comprehensive_MDRestrictionCode_ `xml:"GM03_2_1Comprehensive.Comprehensive.MD_RestrictionCode_"`
}

type GM03_2_1Comprehensive_Comprehensive_MDRestrictionCode_ struct {
	Value string `xml:"value"`
}

type OtherConstraints struct {
	GM03_2_1Core_Core_PTFreeText []GM03_2_1Core_Core_PTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type GM03_2_1Core_Core_MDResolution struct {
	TID                  string               `xml:"TID,attr"`
	MDDataIdentification MDDataIdentification `xml:"MD_DataIdentification"`
	EquivalentScale      EquivalentScale      `xml:"equivalentScale"`
}

type MDDataIdentification struct {
	REF string `xml:"REF,attr"`
}

type EquivalentScale struct {
	REF string `xml:"REF,attr"`
}

type GM03_2_1Core_Core_MDRepresentativeFraction struct {
	TID         string `xml:"TID,attr"`
	Denominator int    `xml:"denominator"`
}

type GM03_2_1Core_Core_EXExtent struct {
	TID                  string               `xml:"TID,attr"`
	Description          Description          `xml:"description"`
	MDDataIdentification MDDataIdentification `xml:"MD_DataIdentification"`
}

type GM03_2_1Core_Core_EXExtentgeographicElement struct {
	EXExtent          EXExtent          `xml:"EX_Extent"`
	GeographicElement GeographicElement `xml:"geographicElement"`
}

type EXExtent struct {
	REF string `xml:"REF,attr"`
}

type GeographicElement struct {
	REF string `xml:"REF,attr"`
}

type GM03_2_1Core_Core_EXGeographicBoundingBox struct {
	TID                string  `xml:"TID,attr"`
	NorthBoundLatitude float64 `xml:"northBoundLatitude"`
	SouthBoundLatitude float64 `xml:"southBoundLatitude"`
	EastBoundLongitude float64 `xml:"eastBoundLongitude"`
	WestBoundLongitude float64 `xml:"westBoundLongitude"`
}

type GM03_2_1Core_Core_EXBoundingPolygon struct {
	TID     string  `xml:"TID,attr"`
	Polygon Polygon `xml:"polygon"`
}

type Polygon struct {
	Surface Surface `xml:"SURFACE"`
}

type Surface struct {
	Boundary Boundary `xml:"BOUNDARY"`
}

type Boundary struct {
	PolyLine PolyLine `xml:"POLYLINE"`
}

type PolyLine struct {
	Coord []Coord `xml:"COORD"`
}

type Coord struct {
	C1 float64 `xml:"C1"`
	C2 float64 `xml:"C2"`
}

type GM03_2_1Core_Core_DQDataQuality struct {
	Gml320     string     `xml:"gml320,attr"`
	TID        string     `xml:"TID,attr"`
	MDMetadata MDMetadata `xml:"MD_Metadata"`
}

type GM03_2_1Core_Core_DQScope struct {
	TID           string        `xml:"TID,attr"`
	Level         string        `xml:"level"`
	DQDataQuality DQDataQuality `xml:"DQ_DataQuality"`
}

type DQDataQuality struct {
	REF string `xml:"REF,attr"`
}

type GM03_2_1Core_Core_LILineage struct {
	TID           string        `xml:"TID,attr"`
	Statement     Statement     `xml:"statement"`
	DQDataQuality DQDataQuality `xml:"DQ_DataQuality"`
}

type Statement struct {
	GM03_2_1Core_Core_PTFreeText GM03_2_1Core_Core_PTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type GM03_2_1Comprehensive_Comprehensive_MDMetadatalegislationInformation struct {
	MDMetadata             MDMetadata             `xml:"MD_Metadata"`
	LegislationInformation LegislationInformation `xml:"legislationInformation"`
}

type LegislationInformation struct {
	REF string `xml:"REF,attr"`
}

type GM03_2_1Comprehensive_Comprehensive_MDLegislation struct {
	TID               string            `xml:"TID,attr"`
	Country           Country           `xml:"country"`
	Language          Language          `xml:"language"`
	LegislationType   string            `xml:"legislationType"`
	InternalReference InternalReference `xml:"internalReference"`
	Title             Title             `xml:"title"`
}

type CodeISO_CountryCodeISO_ struct {
	Value string `xml:"value"`
}

type InternalReference struct {
	GM03_2_1Core_Core_CharacterString_ GM03_2_1Core_Core_CharacterString_ `xml:"GM03_2_1Core.Core.CharacterString_"`
}

type GM03_2_1Core_Core_CharacterString_ struct {
	Value string `xml:"value"`
}

type OtherCitationDetails struct {
	GM03_2_1Core_Core_PTFreeText GM03_2_1Core_Core_PTFreeText `xml:"GM03_2_1Core.Core.PT_FreeText"`
}

type Series struct {
	REF string `xml:"REF,attr"`
}

type GM03_2_1Comprehensive_Comprehensive_CISeries struct {
	TID  string `xml:"TID,attr"`
	Name Name   `xml:"name"`
}
