// This file is automatically generated. DO NOT EDIT.

package jmdict

type Entry struct {
	EntSeq int     `xml:"ent_seq"`
	KEle   []KEle  `xml:"k_ele"`
	REle   []REle  `xml:"r_ele"`
	Sense  []Sense `xml:"sense"`
}

type Gloss struct {
	GType    *string `xml:"g_type,attr"`
	Lang     *string `xml:"lang,attr"`
	CharData string  `xml:",chardata"`
}

type JMDict struct {
	Entry []Entry `xml:"entry"`
}

type KEle struct {
	KeInf []string `xml:"ke_inf"`
	KePri []string `xml:"ke_pri"`
	Keb   string   `xml:"keb"`
}

type LSource struct {
	LSType   *string `xml:"ls_type,attr"`
	LSWasei  *string `xml:"ls_wasei,attr"`
	Lang     *string `xml:"lang,attr"`
	CharData string  `xml:",chardata"`
}

type REle struct {
	ReInf     []string  `xml:"re_inf"`
	ReNoKanji *struct{} `xml:"re_nokanji"`
	RePri     []string  `xml:"re_pri"`
	ReRestr   []string  `xml:"re_restr"`
	Reb       string    `xml:"reb"`
}

type Sense struct {
	Ant     []string  `xml:"ant"`
	Dial    []string  `xml:"dial"`
	Field   []string  `xml:"field"`
	Gloss   []Gloss   `xml:"gloss"`
	LSource []LSource `xml:"lsource"`
	Misc    []string  `xml:"misc"`
	Pos     []string  `xml:"pos"`
	SInf    *string   `xml:"s_inf"`
	STagK   []string  `xml:"stagk"`
	STagR   []string  `xml:"stagr"`
	XRef    []string  `xml:"xref"`
}
