// This file is automatically generated. DO NOT EDIT.

package gml

import "time"

type Arc struct {
	Pos []string `xml:"pos"`
}

type ArcByCenterPoint struct {
	EndAngle   float64 `xml:"endAngle"`
	Pos        *string `xml:"pos"`
	PosList    string  `xml:"posList"`
	Radius     float64 `xml:"radius"`
	StartAngle string  `xml:"startAngle"`
}

type BaseCurve struct {
	Curve Curve `xml:"Curve"`
}

type BoundedBy struct {
	Envelope *Envelope `xml:"Envelope"`
	Null     *string   `xml:"Null"`
}

type CompositeCurve struct {
	CurveMember []CurveMember `xml:"curveMember"`
}

type Curve struct {
	ID       string     `xml:"id,attr"`
	Segments []Segments `xml:"segments"`
}

type CurveMember struct {
	Curve           *Curve           `xml:"Curve"`
	OrientableCurve *OrientableCurve `xml:"OrientableCurve"`
}

type CurveMembers struct {
	Curve      []Curve      `xml:"Curve"`
	LineString []LineString `xml:"LineString"`
}

type Envelope struct {
	LowerConder string   `xml:"lowerConder"`
	LowerCorner *string  `xml:"lowerCorner"`
	Pos         []string `xml:"pos"`
	UpperCorner string   `xml:"upperCorner"`
}

type Exterior struct {
	LinearRing *LinearRing `xml:"LinearRing"`
	Ring       *Ring       `xml:"Ring"`
	Shell      *Shell      `xml:"Shell"`
}

type GeodesicString struct {
	PosList string `xml:"posList"`
}

type Interior struct {
	LinearRing LinearRing `xml:"LinearRing"`
}

type LineString struct {
	ID      string `xml:"id,attr"`
	PosList string `xml:"posList"`
}

type LineStringSegment struct {
	Pos     []string `xml:"pos"`
	PosList *string  `xml:"posList"`
}

type LinearRing struct {
	Pos     []string `xml:"pos"`
	PosList *string  `xml:"posList"`
}

type MultiCurve struct {
	CurveMembers CurveMembers `xml:"curveMembers"`
}

type MultiPoint struct {
	PointMember []PointMember `xml:"pointMember"`
}

type MultiSurface struct {
	SurfaceMember SurfaceMember `xml:"surfaceMember"`
}

type OrientableCurve struct {
	ID        string    `xml:"id,attr"`
	BaseCurve BaseCurve `xml:"baseCurve"`
}

type Patches struct {
	PolygonPatch []PolygonPatch `xml:"PolygonPatch"`
	Rectangle    *Rectangle     `xml:"Rectangle"`
	Triangle     *Triangle      `xml:"Triangle"`
}

type Point struct {
	ID  string `xml:"id,attr"`
	Pos string `xml:"pos"`
}

type PointMember struct {
	Point Point `xml:"Point"`
}

type Polygon struct {
	ID       string    `xml:"id,attr"`
	Exterior Exterior  `xml:"exterior"`
	Interior *Interior `xml:"interior"`
}

type PolygonPatch struct {
	Exterior Exterior  `xml:"exterior"`
	Interior *Interior `xml:"interior"`
}

type Rectangle struct {
	Exterior Exterior `xml:"exterior"`
}

type Ring struct {
	CurveMember CurveMember `xml:"curveMember"`
}

type Segments struct {
	Arc               *Arc                `xml:"Arc"`
	ArcByCenterPoint  *ArcByCenterPoint   `xml:"ArcByCenterPoint"`
	GeodesicString    []GeodesicString    `xml:"GeodesicString"`
	LineStringSegment []LineStringSegment `xml:"LineStringSegment"`
}

type Shell struct {
	SurfaceMember []SurfaceMember `xml:"surfaceMember"`
}

type Solid struct {
	Exterior Exterior `xml:"exterior"`
}

type Surface struct {
	Patches Patches `xml:"patches"`
}

type SurfaceMember struct {
	Polygon Polygon `xml:"Polygon"`
}

type TimePeriod struct {
	ID            string    `xml:"id,attr"`
	BeginPosition time.Time `xml:"beginPosition"`
	EndPosition   struct{}  `xml:"endPosition"`
}

type Triangle struct {
	Exterior Exterior `xml:"exterior"`
}

type ValidTime struct {
	TimePeriod TimePeriod `xml:"TimePeriod"`
}
