// This file is automatically generated. DO NOT EDIT.

package play

type Act struct {
	Title    string   `xml:"TITLE"`
	Scene    []Scene  `xml:"SCENE"`
	Epilogue Epilogue `xml:"EPILOGUE"`
}

type Epilogue struct {
	Title          string `xml:"TITLE"`
	Speech         Speech `xml:"SPEECH"`
	StageDirection string `xml:"STAGEDIR"`
}

type FrontMatter struct {
	Paragraph []string `xml:"P"`
}

type Line struct {
	CharData       string  `xml:",chardata"`
	StageDirection *string `xml:"STAGEDIR"`
}

type PersonaGroup struct {
	Persona          []string `xml:"PERSONA"`
	GroupDescription string   `xml:"GRPDESCR"`
}

type Personae struct {
	Title        string         `xml:"TITLE"`
	Persona      []string       `xml:"PERSONA"`
	PersonaGroup []PersonaGroup `xml:"PGROUP"`
}

type Play struct {
	Title             string      `xml:"TITLE"`
	FrontMatter       FrontMatter `xml:"FM"`
	Personae          Personae    `xml:"PERSONAE"`
	ScreenDescription string      `xml:"SCNDESCR"`
	PlaySubtitle      string      `xml:"PLAYSUBT"`
	Act               []Act       `xml:"ACT"`
}

type Scene struct {
	Title          string   `xml:"TITLE"`
	StageDirection []string `xml:"STAGEDIR"`
	Speech         []Speech `xml:"SPEECH"`
}

type Speech struct {
	Speaker        string    `xml:"SPEAKER"`
	Line           []Line    `xml:"LINE"`
	StageDirection []*string `xml:"STAGEDIR"`
}
