// Code generated by goxmlstruct. DO NOT EDIT.

package rss

type RSS struct {
	Channel Channel `xml:"channel"`
}

type Channel struct {
	Title          string `xml:"title"`
	Link           []Link `xml:"link"`
	Description    string `xml:"description"`
	Language       string `xml:"language"`
	PubDate        string `xml:"pubDate"`
	LastBuildDate  string `xml:"lastBuildDate"`
	Docs           string `xml:"docs"`
	Generator      string `xml:"generator"`
	ManagingEditor string `xml:"managingEditor"`
	WebMaster      string `xml:"webMaster"`
	Item           []Item `xml:"item"`
}

type Link struct {
	Href     *string `xml:"href,attr"`
	Rel      *string `xml:"rel,attr"`
	Type     *string `xml:"type,attr"`
	CharData string  `xml:",chardata"`
}

type Item struct {
	Title       *string    `xml:"title"`
	Link        Link       `xml:"link"`
	Description string     `xml:"description"`
	PubDate     string     `xml:"pubDate"`
	GUID        string     `xml:"guid"`
	Enclosure   *Enclosure `xml:"enclosure"`
}

type Enclosure struct {
	Length int    `xml:"length,attr"`
	Type   string `xml:"type,attr"`
	URL    string `xml:"url,attr"`
}
