// Code generated by goxmlstruct. DO NOT EDIT.

package osm

import "time"

type OSM struct {
	Bounds   Bounds     `xml:"bounds"`
	Node     []Node     `xml:"node"`
	Way      []Way      `xml:"way"`
	Relation []Relation `xml:"relation"`
}

type Bounds struct {
	MaxLat float64 `xml:"maxlat,attr"`
	MaxLon float64 `xml:"maxlon,attr"`
	MinLat float64 `xml:"minlat,attr"`
	MinLon float64 `xml:"minlon,attr"`
}

type Node struct {
	ID        int       `xml:"id,attr"`
	Lat       float64   `xml:"lat,attr"`
	Lon       float64   `xml:"lon,attr"`
	Timestamp time.Time `xml:"timestamp,attr"`
	Version   int       `xml:"version,attr"`
	Tag       []Tag     `xml:"tag"`
}

type Tag struct {
	K string `xml:"k,attr"`
	V string `xml:"v,attr"`
}

type Way struct {
	ID        int       `xml:"id,attr"`
	Timestamp time.Time `xml:"timestamp,attr"`
	Version   int       `xml:"version,attr"`
	Nd        []Nd      `xml:"nd"`
	Tag       []Tag     `xml:"tag"`
}

type Nd struct {
	Ref int `xml:"ref,attr"`
}

type Relation struct {
	ID        int       `xml:"id,attr"`
	Timestamp time.Time `xml:"timestamp,attr"`
	Version   int       `xml:"version,attr"`
	Member    []Member  `xml:"member"`
	Tag       []Tag     `xml:"tag"`
}

type Member struct {
	Ref  int    `xml:"ref,attr"`
	Role string `xml:"role,attr"`
	Type string `xml:"type,attr"`
}
