name: main
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
    - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
    - name: build
      run: go build ./...
    - name: test
      run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
    - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
    - uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5
      with:
        version: v1.54.2
