name: main
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version:
        - stable
        - oldstable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
      with:
        go-version: ${{ matrix.go-version }}
    - name: build
      run: go build ./...
    - name: test
      run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
    - uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9
      with:
        version: v1.64.5
